import type { Metadata } from "next";
import { Inter,Inconsolata } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });
const consolata = Inconsolata({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={consolata.className}>
        <Navbar />
        <main className="max-w-3xl mx-auto py-20">
        {children}
        </main>
      </body>
    </html>
  );
}
